---
title: "_`r params$species`_ at `r params$island`"
output: 
  html_document:
    self_contained: false
    lib_dir: "docs/libs"
    navbar:
    - { title: "Home", icon: "fa-home", href: "../", align: left }    
params:
  island: "Anacapa Island"
  species: "Alloclinus holderi"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r}
# load libraries ----
library(tidyverse)
library(plotly)
library(shiny)
library(glue)
library(cowplot)
library(here)
library(lubridate)
here <- here::here

# set paths ----
data_spp_rds  <- here("app/data/KFM_1mQuadrat_Summary_1982-2017_SpeciesName.rds")

# read & filter data ----
# params <- list(island = "Anacapa Island", species = "Alloclinus holderi")
d <- read_rds(data_spp_rds) %>% 
  filter(
    IslandName         == params$island,
    AlternateTaxonName == params$species)
stopifnot(nrow(d) > 0)

# plot data ----
theme_set(theme_cowplot()) # font_size=4)) # reduce default font size

g <- ggplot(d, aes(x = SurveyYear, y = MeanDensity_sqm, color = SiteCode, linetype = SiteCode)) +
  geom_point(size = 1, alpha = 0.7, show.legend = FALSE)+
  geom_line(size = 0.5, alpha = 0.7) +
  ggtitle(glue("{params$species} at {params$island}")) +
  ylab("Mean density (n/m^2)")

# make plot interactive ----
ggplotly(g)
```

