---
title: "Species Size Frequencies"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Size frequencies for species by site

```{r}
library(readr)
library(dplyr)
library(tibble)
options(pillar.sigfig = 6)
library(ggplot2)
library(grid)
library(gridExtra)
library(cowplot)

arms_csv <- "~/Gdrive Ecoquants/projects/nps-ecoquants/kelp-forest/ARMs data/KFM_ARMs_RawData_1992-2018.csv"
sites_csv <- "~/Gdrive Ecoquants/projects/nps-ecoquants/kelp-forest/Export_2018.accdb/KFM_SiteInformation.csv"


sp <- "Strongylocentrotus franciscanus"

d_arms  <- read_csv(arms_csv)
d_sites <- read_csv(sites_csv)

# add missing sites with island average longitude
# TODO: get actual longitude and other info for these sites
sc_lon <- filter(d_sites, IslandCode=="SC") %>% pull(Longitude_DD) %>% mean()
d_sites_missing <- tibble(
  IslandCode   = "SC", 
  SiteCode     = sprintf("BRT%d", 1:3),
  Longitude_DD = sc_lon)
d_sites <- bind_rows(d_sites, d_sites_missing)

# View(d_sites %>% arrange(IslandCode, SiteCode))
# table(d$ScientificName)
# table(d$SiteCode)

# islands ordered by longitude
isl_lon <- d_sites %>% 
  group_by(IslandCode) %>% 
  summarize(
    lon_avg = mean(Longitude_DD)) %>% 
  select(IslandCode, lon_avg) %>% 
  arrange(lon_avg)
d_sites$IslandCodeLon <- factor(
  d_sites$IslandCode,
  levels = isl_lon$IslandCode, ordered = T)

# sites ordered by longitude within ordered islands
sit_lon <- d_sites %>% 
  arrange(IslandCodeLon, Longitude_DD) %>% 
  select(SiteCode, Longitude_DD)
d_sites$SiteCodeLon <- factor(
  d_sites$SiteCode,
  levels = sit_lon$SiteCode, ordered = T)

#theme_set(theme_cowplot())
theme_set(theme_bw())

d <- d_arms %>% 
  filter(ScientificName == sp) %>% 
  left_join(
    d_sites %>% 
      select(SiteCode, SiteCodeLon, IslandCode, IslandCodeLon),
    by = c("SiteCode","IslandCode"))
#table(d$IslandCodeLon, useNA = "ifany")
#table(d$SiteCodeLon  , useNA = "ifany")

# d %>% 
#   filter(is.na(IslandCodeLon)) %>% 
#   with(., table(IslandCode, SiteCode))
#           SiteCode
# IslandCode BRT1 BRT2 BRT3
#         SC  586   55  210

d_i_s <- d %>% 
  group_by(IslandCodeLon, SiteCodeLon) %>% 
  summarize(
    one = 1,
    n = n()) %>% 
  group_by(IslandCodeLon) %>% 
  mutate(
    one    = 1,
    nsites = cumsum(one)) %>% 
  rowid_to_column()

g <- ggplot(d, aes(x=SiteCodeLon, y=Size_mm)) + 
  geom_violin(fill="lightblue", alpha=0.5, color=NA) + 
  stat_summary(fun.y=mean  , geom="point", shape=23, size=2, color="blue") +  
  stat_summary(fun.y=median, geom="point", shape=20, size=1, color="black") + 
  theme(
    axis.text.x = element_text(
      angle = 45))
g

# params for annotation_custom() island code
i <- 1
islands <- unique(d_i_s$IslandCodeLon)
i_txt   <- islands[i]
d_i     <- filter(d_i_s, IslandCodeLon == i_txt)
i_xmin  <- min(d_i$rowid) - 1
i_xmax  <- i_xmin + max(d_i$nsites) + 1

g <- g +
  theme(plot.margin = unit(c(1,1,2,1), "lines")) +
  # TODO: convert annotation_custom() to function for all islands
  annotation_custom(
    textGrob(i_txt, just="center"), # y = unit(-0.4, "lines")),
    xmin=i_xmin, xmax=i_xmax, 
    ymin=unit(-13, "lines"), ymax=unit(-13, "lines")) +
  coord_cartesian(clip="off")
g

plotly::ggplotly(g)
```

